### ISSUE TITLE
Improving volunteer pages

### ISSUE THREAD

**Issue by petehuang** [openelections/docs#29]
This builds off a conversation I had with @dwillis about getting more volunteers. Currently, the Get Involved page and the pages it links out to do not directly tell volunteers where help is needed within OpenElections and where those tasks fit into the overall project. As it stands, the pages require volunteers to read (pretty much) everything about the project before they even get a sense about where they can help.

In order to attract more volunteers, we need to push for more outreach, but without a volunteer-friendly resource that boils down what's important for them to know, the outreach is likely to fall flat.

To that end, we should reformat the Get Involved page to follow this or a similar outline:

### Helping OpenElections without programming
1. Metadata Collection (link to current metadata collection page)
2. Converting raw results to data
3. Recruiting more volunteers
4. Github tutorials and other documentation tasks

### Contributing code to OpenElections
1. Writing [scrapers](http://docs.openelections.net/guide/preprocessing/) to convert HTML or PDF results to CSVs.
2. Writing code to implement a state's [processing pipeline](http://docs.openelections.net/guide/) (or parts of it).
3. Addressing [issues on the core repository](https://github.com/openelections/openelections-core/issues).

### Reaching the community
1. Google Groups
2. Github
3. Email
4. Twitter

Each task should link out to a page that gives clear instructions and resources:

### Task description
1. What are the inputs/outputs?
2. Why is this important?

### How to complete it
1. For well-defined tasks, list out as many discrete steps as possible
2. For unclear tasks, list out a preliminary attempt at what the process would look like

### Helpful resources
1. Who has done this before?
2. Videos, tutorials, blog posts
3. As always, Google Group and other forms of comm

By the end, we will have one place to send potential volunteers.

**Comment by petehuang** [comment]
@dwillis can you point us to someone who can help with the list of technical tasks that need work? I'm completely unfamiliar, so I have little idea about where a developer would be useful.

I will start writing the task pages for the non-technical section and setup a pull request for those

**Comment by dwillis** [comment]
@petehuang I can fill in the technical tasks part.

**Comment by dwillis** [comment]
I've built out some new pages and edited others based on this outline; let me know what you think. http://docs.openelections.net/
