### ISSUE TITLE
guide to result files

### ISSUE THREAD

**Issue by rootsmusic** [openelections/docs#45]
I've tried to find a doc about the result files.  Other than granularity, what's the data relationship between [20181106__pa__general__county.csv](https://github.com/openelections/openelections-data-pa/blob/master/2018/20181106__pa__general__county.csv), [20181106__pa__general__precinct.csv](https://github.com/openelections/openelections-data-pa/blob/master/2018/20181106__pa__general__precinct.csv) and the [counties folder](https://github.com/openelections/openelections-data-pa/tree/master/2018/counties)?

**Comment by dwillis** [comment]
@rootsmusic thanks for asking! Granularity is the main difference - county vs precinct levels - but the other difference is that the first two files are statewide files and the ones in the counties folder are individual files for specific counties. We often convert individual counties first and then create a combined statewide file.
